name: Build on push

on:
  push:
    branches:
      - main
      - fix-nightly-build

jobs:
  build:
    uses: ./.github/workflows/build-yocto.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: build
    secrets: inherit
    with:
      url: ${{ needs.build.outputs.artifacts_url }}
