name: Test PR build

on:
  workflow_run:
    workflows: ["Build on PR"]
    types:
      - completed

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with:
      url: ${{ github.event.workflow_run.outputs.artifacts_url }}

